### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by nevrome** [nevrome/currycarbon#4]
- [ ] Check if an input date is in the range of the calCurve to reject it with a meaningful error message
- [ ] Provide an HDR output that is better machine-readable (-q is fine for humans, but --hdrFile should get a more formal structure)
- [ ] Maybe: Calculate median ages as a possible output option
- [ ] Allow for different calCurves (maybe even user provided ones)
- [ ] Sum calibration (might go well with a grouping variable in the input data)
- [ ] Normal distribution vs. Student's t-distribution
- [ ] Resolution option to allow for faster calibration on a lower output resolution. One setting might be to skip calCurve interpolation completely
- [ ] Generally better error handling for the CLI
- [ ] Refactor and document the library to submit to hackage
- [ ] Understand the Bchron algorithm and copy it, if it gives a performance advantage
- [ ] Maybe the matrix multiplication does not have to be performed explicitly, but can be done "one the fly" when the calCurve matrix is constructed. That's less didactically valuable, but could be faster
- [ ] Discuss potential changes for performance gains with more experienced Haskell developers
- [ ] A conda release might make the software more attractive for the bioinf crowd

**Comment by zypeh** [comment]
suggestion: you may try using Z-Data for the vector manipulation. It also include parser utility too, just not sure if the parsing phrase is the bottleneck.

**Comment by nevrome** [comment]
Thanks for the suggestion @zypeh - there are a couple of good vector and matrix libraries I could try, but I fear I don't have the time to experiment extensively. Z-Data looks pretty well maintained, though.
